LOAD DATA LOCAL INFILE 'data/users.csv' INTO TABLE users
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'data/chefs.csv' INTO TABLE chefs
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'data/categories.csv' INTO TABLE categories
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'data/recipes.csv' INTO TABLE recipes
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'data/favorties.csv' INTO TABLE favorties
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'data/ingredient_amounts.csv' INTO TABLE ingredient_amounts
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'data/ratings.csv' INTO TABLE ratings
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'data/cost.csv' INTO TABLE cost
FIELDS TERMINATED 
  BY ',' ENCLOSED 
  BY '"' LINES TERMINATED 
  BY '\n' IGNORE 1 ROWS;